"""initial tables

Revision ID: 2e59263c2ad9
Revises: 
Create Date: 2026-04-29 01:29:27.439123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e59263c2ad9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_uid', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('picture_url', sa.String(length=500), nullable=True),
    sa.Column('real_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('follow_status', sa.Enum('active', 'unfollowed', name='follow_status_enum'), nullable=False),
    sa.Column('followed_at', sa.DateTime(), nullable=True),
    sa.Column('unfollowed_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('line_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_users_line_uid'), ['line_uid'], unique=True)

    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('tep_response', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='action_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['line_user_id'], ['line_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_logs_line_user_id'), ['line_user_id'], unique=False)

    op.create_table('push_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_user_id', sa.Integer(), nullable=False),
    sa.Column('tep_event_id', sa.Integer(), nullable=True),
    sa.Column('push_type', sa.String(length=50), nullable=False),
    sa.Column('flex_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'failed', name='push_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['line_user_id'], ['line_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_logs_line_user_id'), ['line_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_logs_tep_event_id'), ['tep_event_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_user_id', sa.Integer(), nullable=False),
    sa.Column('tep_temple_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['line_user_id'], ['line_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_user_id', 'tep_temple_id', name='uq_user_temple')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_line_user_id'), ['line_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_tep_temple_id'), ['tep_temple_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_tep_temple_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_line_user_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('push_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_logs_tep_event_id'))
        batch_op.drop_index(batch_op.f('ix_push_logs_line_user_id'))

    op.drop_table('push_logs')
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_logs_line_user_id'))

    op.drop_table('action_logs')
    with op.batch_alter_table('line_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_users_line_uid'))

    op.drop_table('line_users')
    # ### end Alembic commands ###
